// apps/web/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";

// 🔴 HAPUS/KOMENTAR BAGIAN INI BIAR GAK DOWNLOAD FONT
/*
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Hapus variabel ${geistSans.variable} dll dari className */}
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}